/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/worker-configuration.d.ts` (hash: b3305ec28a31208a7eda4e2c38a5e48f)
interface __BaseEnv_Env {
	AI: Ai;
	TEAM_DOMAIN: string;
	OWNER_EMAIL: string;
	OWNER_USER_ID: string;
	OWNER_TIMEZONE: string;
	MODEL_ID: string;
	AI_GATEWAY_ID: string;
	ACCESS_AUD: string;
	PiAgent: DurableObjectNamespace<import("./worker").PiAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "PiAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEAM_DOMAIN" | "OWNER_EMAIL" | "OWNER_USER_ID" | "OWNER_TIMEZONE" | "MODEL_ID" | "AI_GATEWAY_ID" | "ACCESS_AUD">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}